
app_repo: "https://github.com/muxx/sre-hello-world.git"
app_version: "v1.0.0"
deploy_path: "/opt/sre-app"

postgres_db: ${{ vars.DB_NAME }}
postgres_user: ${{ vars.DB_USER }}




# доли от RAM
ram_os_reserve: 0.2
ram_postgres: 0.35
ram_php: 0.30
ram_buffer: 0.15


# PostgreSQL tuning (RAM-based)
pg_memory_mb: "{{ (ansible_memtotal_mb * ram_postgres) | int }}"
pg_shared_buffers: "{{ (pg_memory_mb * 0.30) | int }}MB"
pg_effective_cache_size: "{{ (pg_memory_mb * 0.80) | int }}MB"
pg_work_mem: "16MB"
pg_maintenance_work_mem: "64MB"
pg_max_connections: 5