- name: Create DB user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    state: present
    login_unix_socket: /var/run/postgresql

- name: Create database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
    state: present
    login_unix_socket: /var/run/postgresql


- name: Check if table author exists
  become_user: postgres
  community.postgresql.postgresql_query:
    db: "{{ postgres_db }}"
    login_host: localhost
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    query: "SELECT to_regclass('public.author')"
  register: author_table


- name: Run init script
  environment:
    PGHOST: localhost
    POSTGRES_USER: "{{ postgres_user }}"
    PGPASSWORD: "{{ postgres_password }}"
    POSTGRES_DB: "{{ postgres_db }}"
  command: bash /opt/sre-app/docker/images/postgres/init-extensions.sh
  when: author_table.query_result[0].to_regclass is none

# Открываем базу для подсети докера
- name: Set listen_addresses to all
  lineinfile:
    path: "/etc/postgresql/18/main/postgresql.conf"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"

- name: Allow docker network access to PostgreSQL
  lineinfile:
    path: "/etc/postgresql/18/main/pg_hba.conf"
    insertafter: EOF
    line: "host    all     all     172.18.0.0/16     md5"



- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted